routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','MainController@Index')->name('Index');
Route::get('portfolio.html','MainController@Projects')->name('Projects');
Route::get('web_portfolio.html','MainController@WebProjects')->name('WebProjects');
Route::get('mobile_portfolio.html','MainController@MobileProjects')->name('MobileProjects');
Route::get('branding_portfolio.html','MainController@BrandingProjects')->name('BrandingProjects');
Route::get('contacts.html','MainController@Contacts')->name('Contacts');
Route::get('customer-reviews.html','MainController@CustomerReviews')->name('CustomerReviews');
Route::get('about-us.html','MainController@AboutUs')->name('AboutUs');
Route::get('about.html','MainController@AboutUs')->name('AboutUs');

Route::get('internetmagazin.html','MainController@Shop')->name('Shop');
Route::get('korporativniysite.html','MainController@CorporateSite')->name('CorporateSite');
Route::get('razrabotkabrandbook.html','MainController@Brand')->name('Brand');
Route::get('videoinfografika.html','MainController@Video')->name('Video');
Route::get('smm.html','MainController@SMM')->name('SMM');
Route::get('landingpage.html','MainController@Landing')->name('Landing');
Route::get('services.html','MainController@Services')->name('Services');
Route::get('razrabotkamobilnihprilozheniy.html','MainController@MobileApps')->name('MobileApps');
Route::get('posts','MainController@Posts')->name('Posts');
Route::get('post/{id}','MainController@PostPage')->name('PostPage');
Route::get('game.html','MainController@Game')->name('Game');
Route::get('{url}','MainController@Work')->name('Work');
Route::get('admin/login','AdminController@Login')->name('Login');
Route::post('admin/log','AdminController@Log')->name('Log');



Route::name('admin.')->prefix('admin/')->middleware(['adminCheck'])->group(function(){
    Route::get('main','AdminController@Main')->name('Main');
    Route::post('update/post','AdminController@UpdatePost')->name('UpdatePost');
    Route::get('edit/post/{id}','AdminController@EditPost')->name('EditPost');
    Route::get('projects','AdminController@Projects')->name('Projects');
    Route::post('upload','AdminController@Upload')->name('Upload');
    Route::get('edit/project/{id}','AdminController@EditProject')->name('EditProject');
    Route::get('delete/{id}','AdminController@DeleteProject')->name('DeleteProject');
    Route::get('delete/WebDelete/{id}/{key}','AdminController@deleteWeb')->name('DeleteWeb');
    Route::get('custom/answer/{id}','AdminController@CustomAnswer')->name('CustomAnswer');
    Route::post('find/project','AdminController@FindProject')->name('FindProject');
    Route::get('settings/','AdminController@Settings')->name('Settings');
    Route::post('setting/edit','AdminController@SettingEdit')->name('SettingEdit');
    Route::get('logotypes','AdminController@Logotypes')->name('Logotypes');
    Route::post('add/logotype','AdminController@AddLogotype')->name('AddLogotype');
    Route::get('delete/logotype/{id}','AdminController@DeleteLogotype')->name('DeleteLogotype');
    Route::get('reviews','AdminController@Reviews')->name('Reviews');
    Route::get('delete/review/{id}','AdminController@DeleteReview')->name('DeleteReview');
    Route::post('create/review','AdminController@CreateReview')->name('CreateReview');
    Route::get('posts','AdminController@Posts')->name('Posts');
    Route::get('delete/post/{id}','AdminController@DeletePost')->name('DeletePost');
    Route::post('create/post','AdminController@CreatePost')->name('CreatePost');
    Route::get('meta/tags/','AdminController@MetaTags')->name('MetaTags');
    Route::get('certificates','AdminController@Certificates')->name('Certificates');
    Route::post('add/certificate','AdminController@AddCertificate')->name('AddCertificate');
    Route::get('tests','AdminController@Tests')->name('Tests');
    Route::get('delete/certificate/{id}','AdminController@DeleteCertificate')->name('DeleteCertificate');
    Route::post('create/test','AdminController@createTest')->name('createTest');
    Route::get('test/{id}','AdminController@Test')->name('Test');
    Route::post('create/step','AdminController@createStep')->name('createStep');
    Route::get('step/{id}','AdminController@Step')->name('Step');
    Route::post('answer','AdminController@createAnswer')->name('createAnswer');
    Route::get('delete/question/{id}','AdminController@DeleteQuestion')->name('DeleteQuestion');
    Route::get('delete/answer/{id}','AdminController@DeleteAnswer')->name('DeleteAnswer');
    Route::get('delete/custom/{id}','AdminController@DeleteCustom')->name('DeleteCustom');
    Route::post('update/project','AdminController@UpdateProject')->name('Update');
});

resources/views/admin/certificates.blade.php
@extends('layouts.admin')
@section('content')
<div class="col-lg-12">

    <div class="card p-3">
        <h2>
            Добавить благодарственное письмо
        </h2>
        <form action="{{route('admin.AddCertificate')}}" method="post" enctype="multipart/form-data">
            {{csrf_field()}}
            <div class="form-group">
                <label for="">Загрузите фото благодарственного письма</label>
                <input type="file" name="certificate" id="" class="form-control p-1">
            </div>
            <div class="form-group">
                <label for="">Загрузите фото логотипа</label>
                <input type="file" name="logo" id="" class="form-control p-1">
            </div>
            <div class="form-group">
                <input type="text" name="link" id="" class="form-control" placeholder="Введите ссылку на сайт">

            </div>
            <div class="form-group">
                <input type="text" name="title" class="form-control" placeholder="Введите имя партнера">
            </div>
            <div class="form-group">
                <input type="submit" value="Добавить" class="btn btn-primary">
            </div>

        </form>
    </div>
</div>
<div class="col-lg-12">
    {{$certificates->links()}}
</div>
@foreach($certificates as $certificate)

    <div class="col-lg-4 mt-5">
        <div class="card p-3">
            <img src="{{asset($certificate['image_link'])}}" alt="" class="w-100">
            <div class="d-flex mt-5">
                <img src="{{asset($certificate['mini_logo'])}}" alt="" class="mini_logo">
                <a href="{{$certificate['link']}}">{{$certificate['title']}}</a>
            </div>
            <button class=" mt-5 btn btn-danger" onclick="window.location.href='{{route('admin.DeleteCertificate',$certificate['id'])}}'">Удалить</button>
        </div>

    </div>
@endforeach

<style>
    .mini_logo{
        width: 100px;
    }
</style>
@endsection

resources/views/admin/edit_post.blade.php
@extends('layouts.admin')
@section('content')

    <link href="https://cdn.quilljs.com/1.3.6/quill.snow.css" rel="stylesheet">
    <script src="https://cdn.quilljs.com/1.3.6/quill.js"></script>
    <div class="col-lg-12">
        <div class="card p-3">
            <form action="{{route('admin.UpdatePost')}}" method="post">
                {{csrf_field()}}
                <div class="form-group">
                    <input type="hidden" name="post_id" value="{{$post['id']}}">
                    <input type="text" class="form-control mb-5" name="title" placeholder="Название" value="{{$post['title']}}">
                    <textarea name="text" id="summernote" class="form-control mt-4" cols="30" rows="5">{!! $post['text'] !!}</textarea>
                </div>
                <div class="form-group">
                    <input type="submit" value="Добавить" class="btn btn-primary">
                </div>
            </form>
        </div>
    </div>

@endsection

resources/views/admin/logotypes.blade.php
@extends('layouts.admin')
@section('content')

    <div class="col-lg-12">
        <div class="card w-100 p-3 mb-5">
            <h2>
                Добавить логотип
            </h2>
            <form action="{{route('admin.AddLogotype')}}" method="post" enctype="multipart/form-data">
                {{csrf_field()}}
                <div class="form-group">
                    <input type="file" name="image_path" id="" class="form-control-file form-control p-1" accept="image/x-png,image/gif,image/jpeg">
                    <input type="submit" value="Добавить" class="btn btn-primary mt-2">
                </div>

            </form>
        </div>
    </div>
    @foreach($logotypes as $logotype)
    <div class="col-lg-4">

        <div class="card p-5 w-100">

            <img src="{{asset($logotype['image_path'])}}" alt="" class="w-100">
        </div>
        <button onclick="window.location.href='{{route('admin.DeleteLogotype',$logotype['id'])}}'"  class="btn btn-danger btn_main">Удалить</button>
    </div>



@endforeach
<div class="col-lg-12">
    {{$logotypes->links()}}
</div>
<style>
    .btn_main{
        position: absolute;
        top: 10px;
        right: 20px;
    }

</style>

@endsection

resources/views/admin/main.blade.php
@extends('layouts.admin')
@section('content')

    <div class="col-lg-12">
        <div class="card d-flex justify-content-center align-items-center p-4">
            <form action="{{route('admin.Upload')}}" class="w-100" enctype="multipart/form-data" method="post">
                {{csrf_field()}}
                <div class="d-flex justify-content-center">
                    <h3>
                        Добавить работу для страницы портфолио
                    </h3>
                </div>
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="Название проекта" name="title" value="{{ old('title') ?? $project->title ?? '' }}">

                </div>
                <div class="form-group">
                    <label for="logo_file" class="">Загрузите логотип</label>
                    <br>

                    <input type="file" name="logo_path" id="logo_file" class="form-control-file form-control p-1" accept="image/x-png,image/gif,image/jpeg" >
                </div>
                <div class="form-group">
                    <label for="background_file">Выберите файл для заднего фона</label>
                    <br>
                    <input type="file" name="background_path" id="background_file" class="form-control-file form-control p-1" accept="image/x-png,image/gif,image/jpeg" >
                </div>
                <div class="form-group ">
                    <label for="main_image">Загрузите основное фото </label>
                    <br>
                    <input type="file" name="main_image" id="main_image" value="{{ old('main_image') ?? $project->main_image ?? '' }}" class="form-control-file form-control p-1" accept="image/x-png,image/gif,image/jpeg" >
                </div>
                <div class="form-group form-inline">
                    <label for="web">Веб</label>
                    <input type="checkbox" onchange="webImage()" name="web" id="web">
                    <label for="mobile">Мобильное приложение</label>
                    <input type="checkbox" onchange="mobileImage()" name="mobile" id="mobile">
                    <label for="branding">Продвижение</label>
                    <input type="checkbox" name="branding" id="branding">

                </div>
                <div class="form-group d-none" id="web_image_page">
                    <label for="web_image">Загрузите страницу сайта</label>
                    <br>
                    <input type="file" name="web_image[]" multiple id="web_image" class="form-control-file form-control p-1" accept="image/x-png,image/gif,image/jpeg" >
                </div>
                <div class="form-group d-none" id="mobile_image_page">
                    <label for="mobile">Загрузите изображения приложения</label>
                    <br>
                    <input type="file" name="mobile_images[]" multiple id="mobile_image" class="form-control-file form-control p-1" accept="image/x-png,image/gif,image/jpeg" >
                </div>
                <div class="form-group">
                    <input type="text" name="link" id="" class="form-control" value="{{ old('link') ?? $project->link ?? '' }}" placeholder="Введите url страницу для портфолио">
                </div>
                <div class="form-group d-none" id="web_page_link">
                    <input type="text" name="link_to_page" class="form-control" placeholder="Введите url страницу сайта">
                </div>
                <div class="form-group">
                    <label for="letter">Загрузите благодарственное письмо</label> <br>

                    <input type="file" id="letter" name="letter_path" class="form-control-file form-control p-1" accept="application/pdf,application/vnd.ms-excel" >
                </div>
                <div class="form-group">
                <label for="summernote">Напишите отзыв клиента</label> <br>

<<<<<<< HEAD
                    <textarea name="review"  class="form-control" id="summernote" cols="30" rows="5" placeholder="Напишите отзыв клиента"></textarea>
=======
                    <textarea name="review"  class="form-control" id="summernote" cols="30" rows="5" placeholder="Напишите отзыв клиента">{{ old('review') ?? $project->review ?? '' }}</textarea>
>>>>>>> d4d3a4a54e4df97afd186f6017d7b03e6c71e6e7
                </div>
                <div class="form-group">
                    <input type="text" name="technologies" class="form-control" id="" value="{{ old('technologies') ?? $project->technologies ?? '' }}" placeholder="Напишите стек технологий">
                </div>
                <div class="form-group">
                    <textarea name="description" id="summernote1" class="form-control" cols="30" rows="5" placeholder="Описание работы">{{ old('description') ?? $project->description ?? '' }}</textarea>
                </div>
                <div class="form-group d-flex justify-content-center">
                    <input type="submit" value="Создать" class="btn btn-primary">
                </div>
            </form>
        </div>
    </div>
    <script>
        $(document).ready(function() {
            $('#summernote1').summernote();
        });
    </script>


@endsection

resources/views/admin/posts.blade.php
@extends('layouts.admin')
@section('content')
    <link href="https://cdn.quilljs.com/1.3.6/quill.snow.css" rel="stylesheet">
    <script src="https://cdn.quilljs.com/1.3.6/quill.js"></script>
<div class="col-lg-12">
    <div class="card p-3">
        <form action="{{route('admin.CreatePost')}}" method="post">
            {{csrf_field()}}
            <div class="form-group">
                <input type="text" class="form-control mb-5" name="title" placeholder="Название">
                <textarea name="text" id="summernote" class="form-control mt-4" cols="30" rows="5">Пост</textarea>
            </div>
            <div class="form-group">
                <input type="submit" value="Добавить" class="btn btn-primary">
            </div>
        </form>
    </div>
</div>
    @foreach($posts as $post)
        <div class="col-lg-4 mt-5">
            <div class="card p-3">
                <h5>
                    <b>{{$post['title']}}</b>
                </h5>

                <p>
                    {!! $post['text'] !!}
                </p>
                <button class="btn btn-primary mt-2" onclick="window.location.href='{{route('admin.EditPost',$post['id'])}}'">Редактировать</button>
                <button onclick="window.location.href='{{route('admin.DeletePost',$post['id'])}}'" class="btn btn-danger mt-2">Удалить</button>
            </div>
        </div>
    @endforeach
    <div class="col-lg-12">
        {{$posts->links()}}
    </div>


    <script>
    </script>
@endsection

resources/views/admin/projects.blade.php
@extends('layouts.admin')
@section('content')
    <style></style>

    <link rel="stylesheet" href="{{asset('portfolio/css/style.css')}}">




                <div class="content_works col-lg-12">
                    {{$projects->links()}}
                    <div class="row">



                    @foreach($projects as $project)
                            <div class="modal fade" id="modal_delete_{{$project['id']}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                <div class="modal-dialog" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="exampleModalLabel">Вы уверены что хотите удалить?</h5>
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>

                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
                                            <button type="button" class="btn btn-danger" onclick="window.location.href='{{route('admin.DeleteProject',$project['id'])}}'">Удалить</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        <div class="col-lg-6   pr-0" >
                            <button class="btn btn-primary btn_edit" onclick="window.location.href='{{route('admin.EditProject',$project['id'])}}'">Редактировать</button>
                            <button class="ml-auto btn btn-danger btn_delete" data-toggle="modal" data-target="#modal_delete_{{$project['id']}}">Удалить</button>
                            <div class="card">
                                <div class="logo_image_part "   style="background-image: url({{asset($project->background_path)}})">
                                    <div class="d-flex w-100 justify-content-between align-items-center" style="background: linear-gradient(90deg, #FFFFFF 0.88%, rgba(255, 255, 255, 0.47) 100%);">
                                        <img src="{{asset($project['logo_path'])}}" alt="" >
                                    </div>

                                </div>
                                <div class="go_to_page" onclick="window.location.href='{{route('Work', $project['link'])}}'">
                                    <img src="{{asset('images/arrow_right.svg')}}" alt="">
                                </div>

                                <div class="text_of_work d-flex justify-content-between">
                                    <div class="title">

                                        {{$project['title']}}
                                    </div>
                                    <div class="properties d-flex">
                                        @if($project['web'] == 1)
                                            <div class="property">
                                                web
                                            </div>
                                        @endif
                                        @if($project['mobile'] == 1)
                                            <div class="property">
                                                mobile
                                            </div>
                                        @endif
                                        @if($project['branding'] == 1 )
                                            <div class="property">
                                                branding
                                            </div>
                                        @endif
                                    </div>
                                </div>
                            </div>
                        </div>
                    @endforeach
                    </div>


                </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    <script>
        $(window).ready(function(){
            $('.go_to_page').fadeOut()
        })
        $(".col-lg-6").hover(function(){
            $('.go_to_page').eq($(this).index()).addClass('active')
        }, function(){
            $('.go_to_page.active').removeClass('active')
        });
    </script>
    <style>
        .logo_image_part img{
            width: 100px;
            height: auto;


        }
        .logo_image_part>div{
            align-items: center !important;
            height: 100%;
            padding-top: 40px;
        }
        .logo_image_part{
            background-size: cover;
            background-position: center;
        }
        .content_works .col-lg-6:hover{
            cursor: pointer;
        }
        .go_to_page.active{
            display: flex;
        }
        .go_to_page{
            transition: 0.5s ease;
        }
        .content_menu a.active{
            color: #000;
            padding-bottom: 7px;
            border-bottom: 2px #000 solid;
        }
        .btn_delete{
            position: absolute;
            z-index: 10;
            right: 10px;
            top: 10px;
        }
        .btn_edit{
            position: absolute;
            left: 20px;
            top: 10px;
            z-index: 10;
        }
    </style>
@endsection

resources/views/admin/reviews.blade.php
@extends('layouts.admin')
@section('content')

<div class="col-lg-12 mb-4">
    <div class="card p-3">
        <form action="{{route('admin.CreateReview')}}" method="post">
            {{csrf_field()}}
            <input type="text" class="form-control" name="author" placeholder="Автор">
            <div class="form-group mt-2">
                <textarea  name="review" class="form-control" id="summernote" cols="30" rows="10">Отзыв</textarea>
            </div>
            <input type="submit" class="btn btn-primary">
        </form>
    </div>
</div>
    @foreach($reviews as $review)
        <div class="col-lg-4">
            <div class="card p-3">
                <h5>
                    <b>{{$review['author']}}</b>
                </h5>
                <p>
                    {!! $review['review'] !!}
                </p>
                <button class="btn btn-danger" onclick="window.location.href='{{route('admin.DeleteReview',$review['id'])}}'">Удалить</button>
            </div>

        </div>

    @endforeach

    <div class="col-lg-12">
        {{$reviews->links()}}
    </div>



@endsection

resources/views/admin/step.blade.php
@extends('layouts.admin')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <h3 class="text-center">
                        {{$step->question}}

                    </h3>
                    <h5>
                        Добавить ответ
                    </h5>
                    <form action="{{route('admin.createAnswer')}}" method="post">
                        {{csrf_field()}}
                        <div class="form-group mt-2">
                            <input type="text" class="form-control" name="name" placeholder="Моб приложения">
                        </div>
                        <p><select class="admin__select" name="category">
                            <option selected disabled>Следующий вопрос</option>
                            @foreach (App\TestStep::get() as $answer)
                            <option value="{{ $answer->id }}">{{ $answer->question }}</option>
                            @endforeach
                            </select>
                            </p>
                            <label for="input-text">Текстовое поле</label>
                            <input type="checkbox" name="input-text" id="input-text">
                        <input type="hidden" name="test_step_id" value="{{$step->id}}">
                        <div class="form-group text-center">
                            <a href='{{route('admin.CustomAnswer',$step->id)}}'
                             class='btn btn-primary'>Кастомные ответы</a>
                            <input type="submit" class="btn btn-primary">
                        </div>
                    </form>
                </div>

            </div>
            @foreach($answers as $answer)
                <div class="col-lg-4">
                    <div class="card card_step">
                        <h5>
                            {{$answer->answer}}
                        </h5>
                        <h5>
                            {{$answer->counter}}
                        </h5>
                        <a href="{{route('admin.DeleteAnswer',$answer->id)}}" class="btn btn-danger">
                            Удалить
                        </a>
                    </div>
                </div>
            @endforeach
        </div>
    </div>
    <style>
        .card_step{
            display: flex;
            justify-content: space-between;
            flex-direction: row;
            margin-top: 10px;
            margin-bottom: 10px;
            padding-top: 15px;
            padding-bottom: 15px;
            padding-left: 10px;
            padding-right: 10px;
            vertical-align: middle;

        }
        .col-12 .card
        {
            padding:20px 15px;
        }
        .admin__select {
            outline: none;
            display: block;
            width: 100%;
            height: calc(1.5em + .75rem + 2px);
            padding: .375rem .75rem;
            font-size: 1rem;
            font-weight: 400;
            color: #6e707e;
            background-color: #fff;
            border: 1px solid #d1d3e2;
            border-radius: .35rem;
            margin-top: 10px;
            cursor: pointer;
        }
    </style>
@endsection

resources/views/admin/test.blade.php
@extends('layouts.admin')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <h3 class="text-center">
                        {{$test->name}}

                    </h3>
                    <h5>
                        Добавить вопрос
                    </h5>
                    <form action="{{route('admin.createStep')}}" method="post">
                        {{csrf_field()}}
                        <div class="form-group mt-2">
                            <input type="text" class="form-control" name="name" placeholder="Например какие сайты вам нравятся?">
                        </div>
                        <input type="hidden" name="test_id" value="{{$test->id}}">
                        <div class="form-group text-center">
                            <input type="submit" class="btn btn-primary">
                        </div>
                    </form>
                </div>

            </div>
            @foreach($steps as $step)
                <div class="col-lg-4">
                    <div class="card card_step">
                        <h5>
                            {{$step->question}}
                        </h5>
                        <a href="{{route('admin.DeleteQuestion',$step->id)}}" class="btn btn-danger">
                            Удалить
                        </a>
                        <a href="{{route('admin.Step',$step->id)}}" class="btn btn-primary">
                            Перейти
                        </a>
                    </div>
                </div>
            @endforeach
        </div>
    </div>
    <style>
        .card_step{
            align-items: center;
            display: flex;
            justify-content: space-between;
            flex-direction: row;
            margin-top: 10px;
            margin-bottom: 10px;
            padding-top: 15px;
            padding-bottom: 15px;
            padding-left: 10px;
            padding-right: 10px;
            vertical-align: middle;

        }
        .col-12 .card
        {
            padding:20px 15px;
        }
        .admin__select {
            outline: none;
            display: block;
            width: 100%;
            height: calc(1.5em + .75rem + 2px);
            padding: .375rem .75rem;
            font-size: 1rem;
            font-weight: 400;
            color: #6e707e;
            background-color: #fff;
            border: 1px solid #d1d3e2;
            border-radius: .35rem;
            margin-top: 10px;
            cursor: pointer;
        }
    </style>
@endsection

resources/views/admin/tests.blade.php
@extends('layouts.admin')
@section('content')
    <div class="col-12">
        <div class="card">
            <h5 class="text-center">
                Создать опрос
            </h5>
            <form action="{{route('admin.createTest')}}" method="post" class="">
                {{csrf_field()}}
                <div class="form-group">
                    <h6 class="text-center">Название вашего опроса</h6>
                    <input type="text" class="form-control" placeholder="Например ваши пожелания к сайтам" name="name">

                </div>

                <div class="form-group d-flex justify-content-center">
                    <input type="submit" value="Создать" class="btn btn-primary">
                </div>
            </form>
        </div>
    </div>
    @foreach($tests as $test)
        <div class="col-lg-4">
            <div class="card d-flex justify-content-between test_card">
                <h4>
                    {{$test->name}}
                </h4>
                <a href="{{route('admin.Test',$test->id)}}" class="btn btn-primary">Перейти</a>
            </div>
        </div>
    @endforeach


    <style>
        .test_card{
            margin-top: 20px;
            display: flex;
            flex-direction: row;
        }
        .card{
            padding: 15px;
        }
    </style>

@endsection